### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ckeeney** [PeterKottas/guestbell-forms#1]
I tried to add this project to a new next.js project.  I got the following error.
```
Module not found: Error: Can't resolve 'react-ink' in 

'/home/ckeeney/src/myapp/node_modules/guestbell-forms/build'
```
I installed `react-ink` but then I got the following error.
```
Module not found: Error: Can't resolve 'react-onclickoutside' in 

'/home/ckeeney/src/myapp/node_modules/guestbell-forms/build'
```

I didn't go any further than this.  Is the build broken?

**Comment by PeterKottas** [comment]
Hi there. Thanks for getting in touch. We care very much about the size of the final package. That's why all dependencies that we used are defined as peer dependencies. Therefore it's not included and you can feel free to install your own (and maintain the version which gives you more control). Npm and yarn both gives you warning about missing peer deps.

Also some of these deps are optional for example react-ink is only required if you turn on the ink effects on buttons (on by default)

Furthermore, if you rly rly care about the size of the lib. You can also import the components like this:
```
import Button from 'guestbell-forms/lib/components/button';
```

Please note though that this points to typescript files. We will eventually transpile these and export as

```
import Button from 'guestbell-forms/components/button';
```

This is not done yet though.

We will also need to update the docs cause right now it's definitely confusing. It's an internal product that we use in GuestBell, we just decided to open source it because "why not?".

**Comment by mehmetyilmaz001** [comment]
Hi There,

I tried to ad dependencies but something different error occurred

/node_modules/guestbell-forms/build/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: '.\node_modules\guestbell-forms\build\components\inputHeader\InputHeader'.

Thanks
